oracc/nammu

python/nammu/view/AtfAreaView.py
The text in the edit pane and and the styled document may be slightly… different
It seems like the styled document normalizes the windows line endings away so make sure that we use the same text for lexing that we are syntax highlighting
=> Fix syntax highlighting on windows

python/nammu/controller/NammuController.py
Making the Save option overwrite opened file. If file was started from scratch and has no filename, then prompt JFileChooser.
=> Simplifying save file functionality

.gitignore, pom.xml, python/nammu/controller/AtfAreaController.py, python/nammu/controller/ConsoleController.py, python/nammu/controller/NammuController.py, python/nammu/utils/NammuConsoleHandler.py, python/nammu/view/AtfAreaView.py, python/nammu/view/AtfEditArea.py, python/nammu/view/ConsoleView.py, python/nammu/view/SyntaxHighlighter.py
Rewrite of `syntax_highlight` so it covers error highlighting as well, so we can simplify the code a little bit and make error highlight persistent.
Also fixed the tooltip clearing functionality.
Still needs some refactoring, so please don't merge yet.
=> Persistent syntax highlight

python/nammu/controller/NammuController.py
When saving as, then canceling from the JFileChooser, the current file is overwritten and a log message appears saying "File ... successfully saved."
=> Bugfix saveasfile displays wrong log message

python/nammu/view/AtfEditArea.py
Solving issue #245 by using a simple regex to strip the the `<a>` tags from the error message before it is displayed as a tooltip.
=> Stripping hyperlink tags from tooltip error messages

python/nammu/controller/AtfAreaController.py, python/nammu/view/AtfAreaView.py, python/nammu/view/AtfEditArea.py
Fixing the issue of error highlighting not persisting on line insertion or deletion, as reported in #243.
Resolved by using a document listener to get changes to a text area, and where there are newlines in those changes, update the dictionary of error lines from the server to reflect the new document structure. For the case of deleted lines it is a bit more messy, as we have to use the keypress listener to record the contents of the text area prior to an edit occurring, and then use the document listener to identify the removed text and then do the same process as with the added text, but decreasing line numbers in the dictionary.
I have found some edge cases where the above did not work properly. These all surround what happens when the cursor is on an error line. Most of this has been …
=> Error highlight 243

python/nammu/controller/NammuController.py, python/nammu/utils/__init__.py, python/nammu/view/NewAtfView.py
This PR fixes two related bugs described in #278 and #279.
The changes made are:
- Fixing the new atf file button so that it does not crash if the default project value is stored in the config file as a string rather than a string within a list
- Warning the user that they are trying to validate a non `*.atf` file rather than sending it to the server where it erroneously is reported as a valid file regardless of errors
- Updating the save and save as dialogues to prompt for `*.atf` files to be saved rather than `all files`
- Created new method to force filenames to have an `*.atf` extension upon save or save as
- Added a new warning when a user tries to load a non-atf file. The file will still load, but the user is warned this could cause problems.
Last thing to do before review and …
=> Fixing file extension problems

python/nammu/controller/NammuController.py, python/nammu/view/EditSettingsView.py
The bug was caused by the syntax highlight method not being called after file load on files with no vertical scroll bars. This has been fixed by adding a call to the initialise syntax highlighting method in a `runlater` thread using swingutils and adding another call to refresh the  edit area styling following new file load.
This resolves issue #285.
=> Fixing the line height bug

python/nammu/controller/AtfAreaController.py, python/nammu/controller/ModelController.py, python/nammu/controller/NammuController.py
This resolves issue #282 by identifying when a must-fragment file has been loaded and warning the user to re save as separate single fragment files if they want to use the feature.
As this feature is experimental and incomplete at present a general warning to that effect has also been added to the console.
To better improve the flow of messages onto the console, the file loaded successfully message has been moved from a `debug` message to an `info` message and the console is refreshed upon new file load, so that these warnings do not persist after the user has resolved them by loading a new single fragment file.
=> Fixing model view problem on trying to load multi fragment files.

python/nammu/view/EditSettingsView.py
Just noticed this bug while I was trying to increase the font-size greater than 30.
=> Changed error message to match validate_fontsize logic

pom.xml
Resolves #302. For some reason, easy_install recently stopped working. This is a temporary work around while we look at changing to pip.
=> Fix easy_install

python/nammu/utils/__init__.py
Fixes #299. There were two issues:
- Paths containing spaces were encoded and not recognised when opening files there.
- When the above caused an error, there was a small bug in the error handling.
This should fix both of these, and also cover the corner case of a path containing an exclamation point, in which case the previous version would also fail (see [the issue comments](https://github.com/oracc/nammu/issues/299#issuecomment-341537955) for more details).
=> Fix path handling when loading

pom.xml, python/nammu/controller/NammuController.py, python/nammu/view/SyntaxHighlighter.py, requirements.txt
This contains 2 line changes for making with new PyOracc changed APIs. Once, you merge https://github.com/oracc/pyoracc/pull/71 , you can then, also merge it. 
pom.xml and requirements.txt url changes are just to pass the test with new Pyoracc. Once all the pull requests are merged, it can be reverted back to ucl website and released as new version for Nammu.
=> Made API changes required with new PyOracc

pom.xml, requirements.txt
@raquel-ucl Now, reverted the url to ucl repository as pyoracc changes are now merged.
=> Reverting to ucl git repo as pyoracc changes are merged.

.travis.yml
Not using hardcoded "`oracc/namu`" makes it possible to run the tests also on forks of this repository
=> Use TRAVIS_REPO_SLUG environment variable in Travis script

python/nammu/controller/AtfAreaController.py, python/nammu/controller/EditSettingsController.py, python/nammu/view/AtfAreaView.py, python/nammu/view/EditSettingsView.py, resources/config/settings.yaml
This will automatically update the font of the related line numbers, too.  Fix #377. Fix #385.
Note: this is based on #376 and thus it should be merged after that PR.  The reason it's based on that PR is because they contain conflicting changes.  If you want to review this PR, just look at the last commit of the series.
=> Directly set the font of edit areas in AtfAreaView.refresh()

python/nammu/controller/NammuController.py, python/nammu/test/test_nammu.py, python/nammu/view/AtfAreaView.py, python/nammu/view/NammuView.py
Fix #387.  I'm not sure this is a superefficient solution as it uses
`NammuController.unsavedChanges()`, which may be a bit too expensive.
=> Add "(*) " to the title bar when there are unsaved changes

python/nammu/controller/NammuController.py, python/nammu/view/AtfAreaView.py
* Initialise members of `NammuController` in the constructor
* In `get_viewport_carets` test the type instead of catching all exceptions
These changes, together with #398, make the failure rate of tests on Travis to drop *sensibly* as far as I could see.  #397 may not be needed in the end.
=> Minor fixes

python/nammu/view/SyntaxHighlighter.py
As explained in the comments I added, for some reason `tok.lineno` is larger than the number of elements of `splittext` (which is the vector containing the lines of the local variable `text`).
For example, it happens that `splittext` has value
```
[u'&P393071 = SAAB 17, 1', u'#p']
```
and `tok.lineno` has value `11`, so we were trying to access `splittext`, which has length 2, at element 10.  Note that `splittext` appears to be somehow "corrupted", while `self.lexer` has the full list of tokens of the same file.  I honestly don't understand why this happens.
The work around (it's not a real fix!) I'm proposing here is to check that `tok.lineno` is equal to or less than the length of `splittext` before trying to access the line, and if not then set `mylength` to 0 (which effectively …
=> Work around issue in syntax highlighter

python/nammu/controller/AtfAreaController.py, python/nammu/view/AtfAreaView.py
This is my initial attempt at fixing #371.  There are two separate issues here:
1. focus stays in the current pane even if the edit being undone is in another pane
2. only when syntax highlighting is on, the caret moves to the second line of the edit area if this panel has focus and the edit to be undone is in the other pane
Currently this PR fixes the first issue, I marked it as draft because it's not yet complete, as I have to:
=> Fix focus when undoing

.gitignore, python/nammu/test/test_yaml_update.py, python/nammu/utils/__init__.py
Includes:
- Addressing recent warning for PyYAML safety (fixes #369)
- Fixing the error of accidentally erasing the config files when running from source, when a local configuration did not exist (fixes #347)
- Various small fixes and improvements to the configuration loading
Still to do:
=> Various YAML updates

python/nammu/controller/NammuController.py
This fixes a warning about undefined `currentFilename` method.
Fixes #401.
=> Initialise `currentFilename` before displaying Nammu

python/nammu/controller/NammuController.py
Before, the tile was set only when saving a new file.
=> Always set title when saving a file

.travis.yml, pom.xml, requirements.txt
We need to add `MarkupSafe` to the list of dependencies because it's required by
mako and we want to pin it to version 1.x, since version 2 has dropped support
for Python 2.
=> Pin version of MarkupSafe
