pom.xml
=> Do some BDD with Cucumber.

pom.xml, src/test/java/uk/ac/ucl/rc/development/oracc/nammu/AppTest.java
It doesn't work yet because by default tests in maven are run before the plugin that installs pytest. Need to modify the POM to run the jython compile plugin earlier, or the tests later.
=> Run pytest from within Jython and as part of mvn test stage

pom.xml, python/nammu/controller/AtfAreaController.py, python/nammu/controller/MenuController.py, python/nammu/controller/NammuController.py, python/nammu/controller/ToolbarController.py, python/nammu/view/AtfAreaView.py, python/nammu/view/NammuView.py
Includes some minor changes to improve text edition behaviour.
=> Prepare Nammu's v0.1 release

python/nammu/controller/NammuController.py
=> JFileChooser improvements [WIP]

README.md, pom.xml, python/nammu/view/NammuView.py
=> Changes in preparation for release v0.1.1.

python/nammu/view/AtfEditArea.py
=> Corrected unicode in error tooltip text.

pom.xml, python/nammu/controller/AtfAreaController.py, python/nammu/controller/ModelController.py, python/nammu/controller/NammuController.py, python/nammu/controller/NewAtfController.py, python/nammu/utils/__init__.py, python/nammu/view/ModelView.py, python/nammu/view/NammuView.py, resources/config/settings.yaml
=> Key bindings

pom.xml, python/nammu/controller/AtfAreaController.py, python/nammu/controller/NammuController.py, python/nammu/view/AtfAreaView.py
=> Undo lemmatisating

python/nammu/utils/__init__.py
=> PyYAML released a new version that doesn't upset maven

python/nammu/controller/AtfAreaController.py, python/nammu/controller/NammuController.py, python/nammu/utils/__init__.py, python/nammu/view/AtfAreaView.py, python/nammu/view/MenuView.py, resources/config/settings.yaml
=> Split screen view

pom.xml, python/nammu/test/test_yaml_update.py, python/nammu/utils/__init__.py, resources/test/jar_settings.yaml, resources/test/user_settings.yaml
=> Setting update fix

python/nammu/view/AtfAreaView.py
=> Added key listener on secondary area of split panels.

python/nammu/controller/AtfAreaController.py, python/nammu/controller/FindController.py, python/nammu/controller/NammuController.py, python/nammu/utils/__init__.py, python/nammu/view/FindView.py, python/nammu/view/SyntaxHighlighter.py, resources/config/settings.yaml
Ctrl+G goes to next match.
Ctrl+R replaces current match.
Ctrl+A replaces all matches in the text.
Ctrl+T syntax highlight switch.
=> Added keystrokes configuration for find/replace window

README.md, python/nammu/controller/AtfAreaController.py, python/nammu/controller/FindController.py, python/nammu/controller/NammuController.py, python/nammu/view/AtfEditArea.py, python/nammu/view/FindView.py, python/nammu/view/SyntaxHighlighter.py, resources/config/settings.yaml
Fixes #198 #195 and part of #190.
=> Matches iterator to list

python/nammu/controller/NammuController.py, python/nammu/view/NewAtfView.py
=> Bugfix reset atf filename when cancelling newfile

python/nammu/controller/AtfAreaController.py, python/nammu/controller/NammuController.py, python/nammu/view/AtfEditArea.py, python/nammu/view/ConsoleView.py, python/nammu/view/SyntaxHighlighter.py
Merging released development code into master.
=> Merge following release of version 0.7.0

python/nammu/view/ConsoleView.py
Simple PR to reimplement the grey background and black text in the console, to give us a better starting point for exposing these parameters.
=> Update console styling from # 256

python/nammu/controller/NammuController.py, python/nammu/controller/WelcomeController.py, python/nammu/view/WelcomeView.py, resources/config/settings.yaml
Still a work in progress, the welcome screen is not very aesthetically pleasing. But meets the minimum requirements for #230.
=> Adding a welcome screen

README.md, pom.xml, resources/config/settings.yaml
This PR covers the updates to the new server address, some changes to the readme and the increment of the Nammu version number from `0.8.0` to `1.0.0`.
The edits to the readme resolve issue #223 and the updated server address resolves issue #267.
=> Create version 1.0.0

python/nammu/utils/__init__.py
Hotfix for bug where settings would not always persist between sessions.
=> Settings hotfix

.travis.yml, python/nammu/test/test_nammu.py, requirements.txt
=> Adapt Travis to test Nammu in headless mode

.travis.yml
=> Deploy JAR file built by Travis to release assets

python/nammu/view/NewAtfView.py, resources/config/settings.yaml
=> Added a few new languages requested by user community.

python/nammu/view/NammuView.py
=> Handle unsaved document when closing the JFrame

python/nammu/controller/AtfAreaController.py, python/nammu/controller/EditSettingsController.py, python/nammu/view/AtfAreaView.py, python/nammu/view/EditSettingsView.py, resources/config/settings.yaml
Fix #372.
In one of the commits I also rationalised the functions that build the menu.
=> Add setting to change size of Arabic pane font size

python/nammu/controller/MenuController.py, python/nammu/controller/NammuController.py, python/nammu/test/test_nammu.py, python/nammu/view/AtfAreaView.py, python/nammu/view/Menu.py, python/nammu/view/MenuView.py
=> Check current status of split view before toggling

python/nammu/view/AtfAreaView.py
Use for the secondary area the style for the main edit area.  Fix #388.
=> Explicitly update font size of secondary area

python/nammu/controller/NammuController.py, python/nammu/test/test_nammu.py
=> Do not send Arabic translation to the server for lemmatisation

python/nammu/controller/NammuController.py, python/nammu/test/test_nammu.py
=> Clear the Arabic pane when closing an Arabic file

.travis.yml, python/nammu/controller/EditSettingsController.py, python/nammu/controller/ModelController.py, python/nammu/controller/NammuController.py, python/nammu/controller/WelcomeController.py, python/nammu/view/AtfAreaView.py, python/nammu/view/AtfEditArea.py, python/nammu/view/ConsoleView.py, python/nammu/view/WelcomeView.py
Mostly remove set/imported but unused variables
=> Small code cleanup

python/nammu/controller/AtfAreaController.py, python/nammu/view/AtfAreaView.py, src/main/java/uk/ac/ucl/rc/development/oracc/ext/TextLineNumber.java
Fix #327.
Preview of the result:
=> Move line numbers of the Arabic pane to the right

python/nammu/controller/ConsoleController.py, python/nammu/controller/NammuController.py, python/nammu/test/test_nammu.py, python/nammu/utils/__init__.py
=> Better handle errors about corrupted configuration files

pom.xml, requirements.txt
=> Pin PyYAML to the latest version compatible with Jython

python/nammu/utils/__init__.py
Fixes #403.  (Note: at the moment three tests are likely to fail because the Oracc server is down)
=> Simplify version checking and patching

python/nammu/utils/__init__.py
Ref https://github.com/oracc/nammu/issues/403#issuecomment-555515288 (Note: three tests may be failing right now because the Oracc server is down)
=> Close all open configuration files
